name: Lint code

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 💚 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: 📦 Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: 🔨 Build packages
        run: pnpm build:packages

      - name: 💄 Run lint
        run: pnpm lint
